token:
  confirmation: 47d06910
  access: vk1.a.WiWQtdgHoRFLwW03ePIaLHEFSZRXtEPaGgHNrQKE9OxU8entmFq91BYMJXsODvocmagogQpwDnsrqknIyo3M_o4dTokLalNhm2EuEhVGvrGV7sQCfj5xoac5UwDYVwQIT6Y5XtHligv6C8LNOYSmF6CMU9rrbalhvssAK4bmU1cHYlIonpf34WEDasv0eYsMOdqMLx8R8naNUh_Mc9Jefg

secret:
  key: aaqqq

server:
  port: 8080